#!/bin/bash
#$ -l h_rt=1:0:0
#$ -l h_vmem=8G
#$ -pe smp 8
#$ -l gpu=1
#$ -cwd
#$ -j y
#$ -l rocky

set -e

# Replace the following line with a program or command
cd /data/home/ec23709/project/FEL
source ./../ReID/reid/bin/activate
python test_fel.py --config_file configs/test/fel/1.yml TEST.WEIGHT '/data/home/ec23709/project/FEL/output/fel_prompt/fel/3/RN50_120.pth' TEST.TEXT '/data/home/ec23709/project/FEL/output/fel_prompt/fel/RN50_text.pth'
python test_fel.py --config_file configs/test/fel/3.yml TEST.WEIGHT '/data/home/ec23709/project/FEL/output/fel_prompt/fel/5/RN50_120.pth' TEST.TEXT '/data/home/ec23709/project/FEL/output/fel_prompt/fel/RN50_text.pth'

# Generated by Job Script Builder on 2025-03-07
# For assistance, please email its-research-support@qmul.ac.uk
# Please cite use of Apocrita in your Research
# See https://docs.hpc.qmul.ac.uk/using/citing/ for details